### ISSUE TITLE
Why is the node to move being cloned here?

### ISSUE THREAD

**Issue by dead-claudia** [adrianhelvik/proposal-move-events#2]
It seems odd to me that you're cloning the node instead of moving the node itself. If the contents are being animated, those animations will reset. Also, procedural JS updates to the original element won't persist in the moved element, despite the moved element itself being modifiable.

**Comment by adrianhelvik** [comment]
Cloning the node would cause issues with overflow. With the snapshot proposal, that is no longer an issue.

I imagine CSS animations could be continued from the exact same point in time as when the snapshot was created. Changes to the original element will indeed not be reflected in the snapshot.

**Comment by dead-claudia** [comment]
> Changes to the original element will indeed not be reflected in the snapshot.

That's why I'm curious why the need to clone it and why the raw node itself couldn't just be used. Just seems redundant and unnecessarily using up resources to me.

**Comment by adrianhelvik** [comment]
With complex layout and css rules, you can't always move an element out of context while preserving which CSS rules affect it. Its width and height sre often different as well. Additionally, overflow hidden/auto can make it impossible to position the element at the given position without moving it out of context.

**Comment by adrianhelvik** [comment]
In a proposal like this, all kinds of optimizations could be made. (Remember: the clone is not part of the page layout i  any way)

**Comment by dead-claudia** [comment]
Oh okay. That makes more sense now, regarding the CSS issue. Still, it doesn't seem like much defensive coding would be necessary anyways, if you simply structure the CSS to properly account for the element while it's in-movement. But I think I'm starting to see the reason for the cloning.

Is the main data flow supposed to be this?

1. On drag start
	1. Create snapshot (mounts clone to new parent)
	1. Set initial element to `visibility: hidden`, blur it, or similar
1. On drag end
	1. If clone lands in original element, revert original element to previous CSS state
	1. If clone lands in different spot, move original element to new location
	1. In either case, remove clone from its parent and let it be collected

**Comment by adrianhelvik** [comment]
Spot on! :)

**Comment by dead-claudia** [comment]
I'll close this, then, since the initial report was due to a misunderstanding.
